package com.example.newsyy;

import android.os.Bundle;
import android.text.method.ScrollingMovementMethod;
import android.widget.TextView;

import androidx.activity.EdgeToEdge;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowInsetsCompat;

public class TermsCondition extends AppCompatActivity {

    TextView textView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        EdgeToEdge.enable(this);
        setContentView(R.layout.activity_terms_condition);

        textView = findViewById(R.id.termsText);
        String para = "Terms of Use\n" +
                "\n" +
                "Welcome to http://navbharattimes.indiatimes.com/ (the \"Site\") managed by Times Internet Limited (hereinafter referred to as the \"Company\", “TIL”, “we” or “our”, which expression shall unless the same be repugnant to the context or meaning thereof be deemed to mean and include its affiliates, subsidiaries, successors in business and assigns).\n" +
                "\n" +
                "ACCEPTANCE OF TERMS OF USE\n" +
                "Please read the following terms and conditions as these terms of use (\"Terms\") constitute a legally binding agreement between you and the Company regarding your browsing, access and use of the Site and any services offered by the Company including but not limited to delivery of specialized content via the Site on any mobile or internet connected device or otherwise (the \"Service\").\n" +
                "\n" +
                "“User”, “you” or “your”: means any person, who is accessing, using the Site, in any manner whatsoever, and is of 18 years of age or older, capable to enter into a legally binding agreement under the laws of India.\n" +
                "By accessing the Site or Service and/or by clicking \"I agree\", you agree to be bound by these Terms. You hereby represent and warrant to the Company that you are at least eighteen (18) years of age or above and are capable of entering, performing and adhering to these Terms and that you agree to be bound by the following terms and conditions. While individuals under the age of 18 may access and use the Service of the Site, they shall do so only with the involvement & guidance of their parents and / or legal guardians, under such Parent /Legal guardian’s registered account. You agree to register prior to uploading any content and / or comment and any other use or services of this Site and provide your details including but not limited to complete name, age, email address, residential address, and contact number.\n" +
                "The Company reserves the right, at its discretion, to change, modify, add, or remove portions of these Terms at any time by posting the amended Terms. Please check these Terms periodically for changes. Your continued use of the site or Services after the posting of changes constitutes your binding acceptance of such changes. In addition, when using any particular services, you may be subject to any posted guidelines, rules, product requirements or sometimes additional terms applicable to such services. All such guidelines, rules, product requirements or sometimes additional terms are hereby incorporated by reference into the Terms.\n" +
                "Further, TIL reserves the right to suspend / cancel, or discontinue any or all channels, products or service at any time without notice, make modifications and alterations in any or all of the content, products and services contained on the Site without prior notice.\n" +
                "YOUR ACCESS OR USE OF THE SITE OR SERVICE SHALL MEAN THAT YOU HAVE READ, UNDERSTAND AND AGREE TO BE BOUND BY THE TERMS OF USE. BY ACCESSING OR USING THE SITE OR SERVICES, YOU ALSO REPRESENT THAT YOU HAVE THE LEGAL AUTHORITY AS PER APPLICABLE LAW (INCLUDING BUT NOT LIMITED TO AGE REQUIREMENT) TO ACCEPT THE TERMS ON BEHALF OF YOURSELF AND/OR ANY OTHER PERSON YOU REPRESENT IN CONNECTION WITH YOUR USE OF THE SITE OR SERVICES. IF YOU DO NOT AGREE TO THE TERMS, YOU ARE NOT AUTHORIZED TO USE THE SITE OR SERVICES.\n" +
                "\n" +
                "CONTENT OWNERSHIP AND LIMITED LICENSE\n" +
                "\"Content\" means and includes without limitation the information, data, text, music, sound, photographs, graphics, video, messages, software or other materials including photos, photographs, pictures or that are otherwise graphical in whole, available on or through the Site or the Services.\n" +
                "\"Company Content\" means Company content, including but not limited to, its proprietary content, Company trademarks and logos made available through the Site and Services, excluding Third Party Content and User Submissions.\n" +
                "\"Third Party Content\" mean any Content that is not owned by the Company and has been contributed by any 3rd party including the User Submissions. You may be able to access, review, display or use third party services, resources, content or information via the Site or the Services.\n" +
                "\"User Submissions\" means the text, data, graphics, images, photos, video or audiovisual content, hypertext links and any other content that the Company allows its users to uploads, posts, flips, compiles or otherwise provided to Company via the Site and Services, as applicable.\n" +
                "Ownership: The Site, Services and the Company Content are protected by copyright, trademark and other applicable laws. Except as expressly provided in these Terms, Company and its licensors exclusively own all right, title and interest in and to the Site, Services, and the Company Content, including all associated intellectual property rights. You may not remove, alter or obscure any copyright, trademark, service mark or other proprietary rights notices incorporated in or accompanying the Site, Services or Company Content. Company claims no ownership interest in any Third Party Content and expressly disclaims any liability concerning those materials.\n" +
                "Limited License: Subject to your compliance with the Terms herein, the Company hereby grants you a personal, limited, non-exclusive, non-transferable, freely revocable license to use the Services for the personal and non-commercial use only. Except for the foregoing limited license, no right, title or interest shall be transferred to you. Content on the Site and/or the Services is provided to you AS IS for your information and personal use only and may not be used, copied, reproduced, distributed, transmitted, broadcast, displayed, sold, licensed, or otherwise exploited for any other purposes whatsoever without the prior written consent of the respective owners. We reserve all rights not expressly granted in and to the Site and/or the Services and the Content. These Terms do not authorize you to, and you may not, reproduce, distribute, publicly display, publicly perform, communicate to the public, make available, create derivative works of or otherwise use or exploit any Third Party Content or User Submissions in violation of applicable copyright law. Any unauthorized use of the Contents or the Services will result in termination of the limited license granted by the Company and cancellation of your membership. Use of Site or the Services for any unauthorised purpose may result in severe civil and criminal penalties. The Company does not promote, foster or condone the copying of Content, or any other infringing activity and the owners of Third Party Content or User Submissions may have the right to seek damages against you for any such violation.\n" +
                "You may print or download extracts from the Site only for your personal / individual, non-commercial use only. You must not retain any copies of these pages saved to disk or to any other storage medium except for the purposes of using the same for subsequent viewing purposes or to print extracts for personal / individual use only.\n" +
                "TIL forbids you from any attempts to resell or put to commercial use any part of the Site; any collection and use of any product listings, descriptions, or prices; any derivative use of the Site or its contents; any downloading or copying of account information for the benefit of any other merchant; any renting, leasing, or otherwise transferring rights to the Site / Service; displaying the name, logo, trademark or other identifier of another person in such a manner as to give the viewer the impression that such other person is a publisher or distributor of the Service on the Site, or any data gathering or extraction tools; or any use of meta tags. You may not (whether directly or through the use of any software program) create a database in electronic or structured manual form by regularly or systematically downloading and storing all or any part of the pages from this site.\n" +
                "No part of the Site may be reproduced or transmitted to or stored in any other web site, nor may any of its pages or part thereof be disseminated in any electronic or non-electronic form, nor included in any public or private electronic retrieval system or service without prior written permission of the Company.\n" +
                "Interactions between Users: You are solely responsible for your interactions (including any disputes) with other users. You understand that Company does not in any way screen users. You are solely responsible for, and will exercise caution, discretion, common sense and judgment in, using the Site and Services and disclosing personal information to other users. You agree to take reasonable precautions in all interactions with other users, particularly if you decide to communicate with Company user offline or meet them in person. Your use of the Site, Services, Company Content, and any other content made available through the Site or Services is at your sole risk and discretion, and Company hereby disclaims any and all liability to you or any third party relating thereto. Company reserves the right to contact users, in compliance with applicable law, in order to evaluate compliance with the rules and policies in this Terms You will cooperate fully with Company to investigate any suspected unlawful, fraudulent or improper activity via the Services.\n" +
                "By making available any User Submissions through the Site and Services, you hereby grant to Company and its users a worldwide, non-exclusive, perpetual, irrevocable, transferable, assignable, royalty-free license, with the right to sublicense, to use, copy, adapt, modify, distribute, publicly display, publicly perform, transmit, stream, broadcast, make available, communicate to the public and otherwise use and exploit such User Submissions through or by means of the Site and the Services and/or to incorporate it in other works in any form, media, or technology now known or later developed throughout the world. Company does not claim any ownership rights in any such User Submissions and nothing in these Terms will be deemed to restrict any rights that you may have to use any such User Submissions. You hereby acknowledge and agree that Company shall not be liable for any uses of your User Submissions by any third party that had access to your User Submissions during the period in which your User Submissions was available on or through the Services. You acknowledge and agree that Company reserves the right to not to publish, display the User Submissions or delete any User Submissions on the receipt of any complaint, that the User Submissions are infringing or in violation of any applicable laws. You acknowledge and agree that you are solely responsible for all User Submissions that you make available through the Site or Services. Accordingly, you represent and warrant that: (a) you either are the sole and exclusive owner of all User Submissions that you make available through the Site or Services or you have all rights, licenses, consents and releases that are necessary to grant to Company the rights in such User Submissions, as contemplated under these Terms; (b) neither the User Submissions nor your accessing, posting, submission or transmittal of the User Submissions or Company’s use of the User Submissions (or any portion thereof) on, through or by means of the Site and the Services or any other permitted use will infringe, misappropriate or violate a third party’s patent, copyright, trademark, trade secret, moral rights or other intellectual property rights, or rights of publicity or privacy, or result in the violation of any applicable law or regulation; and (c) no payments of any kind shall be due to any third party, whether a copyright owner or an agent thereof, for any use made of the User Submissions (or any portion thereof) on, through or by means of the Site and the Services.\n" +
                "By using the Site or the Services, you acknowledge the sole responsibility for and assume all risk arising from your access to, use of or reliance upon any such Third Party Content, or User Submissions and Company disclaims any liability that you may incur arising from your access to, use of or reliance upon such Third Party Content or User Submissions. You acknowledge and agree that Company: (a) is not responsible for the availability or accuracy of such Third Party Content or User Submissions; (b) has no liability to you or any third party for any harm, injuries or losses suffered as a result of your access to, reliance on or use of such Third Party Content or User Submissions; (c) does not undertake or assume any duty to monitor for inappropriate or unlawful content on third party websites or User Submissions; and (d) does not make any promises to remove Third Party Content from being accessed through the Site or the Services.\n" +
                "All the contents of this Site are only for general information. They do not constitute advice and should not be relied upon in making (or refraining from making) any decision. Any specific advice or replies to queries in any part of the Site (if any) is/are the personal opinion of such experts/consultants/persons and are not subscribed to by this Site.\n" +
                "\n" +
                "Exchange of Information qua CHAT & other Community Services (if applicable)\n" +
                "You represent that you are a responsible adult (18 years or above) and you shall be solely responsible for all Content that you upload post or otherwise transmit.\n" +
                "\n" +
                "TIL endeavours to provide a web platform for various community interactions for persons to interact and exchange views with each other. The content posted on such services is by general public therefore the accuracy, integrity or quality of such content cannot be guaranteed. You understand that by using such services, you may be exposed to objectionable matter.\n" +
                "\n" +
                "By using the facility of chat and other community services you agree not to upload, post, or otherwise transmit any matter or views, which are, defamatory, abusive, pervasive, obscene, invasive of another's privacy, hateful, or racially, ethnically or otherwise objectionable. You may also not indulge in cyber stalking, become or create a nuisance for any visitor / user of the Site.\n" +
                "\n" +
                "You may not send, submit, post, or otherwise transmit, material or messages that contain software virus, or any other files that are designed to interrupt, destroy, and negatively affect in any manner whatsoever, any electronic equipment in connection with the use of this Site, or other user's ability to engage in real time exchanges.\n" +
                "\n" +
                "THE SERVICE REGISTRATION AND ACCESS TO USE (If applicable)\n" +
                "Registration: To register for the Services, you may be required to open an account by completing the registration process (i.e. by providing us with current, complete and accurate information as prompted by the applicable registration form). You will also choose a password and a user name. You are entirely responsible for maintaining the confidentiality of your password and account. In particular, as a parent or legal guardian, you acknowledge and assume sole responsibility to ensure that content which is meant for mature audiences (i.e, above the age of majority) is not accessed by children. Hence, you may not share your log in credentials with your children. You expressly agree to absolve the Company of any responsibility / liability in this regard.\n" +
                "TIL shall retain your registration information after cancellation or withdrawal of your registration as required under applicable law(s).\n" +
                "\n" +
                "Facebook Connect: You may also register for the Services by using your Facebook username and password. If, however, you are under 18 years of age, you may log in to the Services using Facebook Connect and utilize the Services only under the supervision of your parent or legal guardian. Using Facebook Connect allows us to personalize and enhance your experience while using the Services, based on your personal information, profile, likes, and other relevant information. When you use this feature, you expressly consent to information about your activity on the Services (i.e. what you have read, what you have liked, ratings given by you, etc.) being continuously released and automatically posted on your Facebook account (which has been used to log in) and made available to your friends on Facebook. You may control the information being shared through Facebook Connect by changing your account / privacy settings. You shall be solely responsible for using this feature and any related compliances with terms of your Facebook account. By registering through Facebook, you agree to the Terms stated herein and in addition to any other specific terms which shall be posted at an appropriate location of the Site. Each registration is for a single individual user only.\n" +
                "Subscription: Your subscription to the Services in a particular geographical territory shall be valid for that territory only and shall not automatically entitle you to access your account from a different geographical territory, unless specifically permitted by the Company.\n" +
                "Geographic Limitation: The Site and/or the Services are controlled and offered by Company from its facilities in the territory of India. Company makes no representations that the Site or Services are appropriate or available for use in other locations. If you are accessing or using the Site or Services from other jurisdictions, you do so at your own risk and you are responsible for compliance with local law. Notwithstanding the foregoing, the Site or Services may contain or provide links to content hosted on website located outside of India.\n" +
                "Access to use: To access the Services, you will be asked to enter your individual user name and password, as chosen by you during your registration. Therefore, the Company does not permit any of the following:-\n" +
                "Any other person sharing your account and Password;\n" +
                "Any part of the Site being cached in proxy servers and accessed by individuals who have not registered with the Company as users of the Site; or\n" +
                "Access through a single account and Password being made available to multiple users on a network.\n" +
                "If the Company reasonably believes that an account and password is being used / misused in any manner, the Company shall reserve the right to cancel access rights immediately without notice, and block access to all users from that IP address. Company reserves the right to reject any user name selected by you and/or revoke your right to any previously selected user name and give such user name to any other person or entity in Company’s sole discretion and without any liability to you. Furthermore, you shall be entirely responsible for any and all activities that occur under your account. You agree to notify the Company immediately of any unauthorized use of your account or any other breach of security. The Company will not be liable for any loss that you may incur as a result of someone else using your password or account, however, you could be held liable for losses incurred by the Company or another party due to someone else using your account or password. If messages sent to an email address provided by you and associated with your account are returned as undeliverable or wrong address; Company reserves the right to terminate your account immediately with or without notice to you and without any liability to you or any third party\n" +
                "Availability: The availability of content through the Site or Services may change from time to time. You are responsible for all Internet access charges. Please check with your Internet provider for information on possible Internet data usage charges.\n" +
                "\n" +
                "BILLING (If Applicable)\n" +
                "By signing up for the Services, you are expressly agreeing that the Company is authorized to charge you subscription fee as per your selected plan, any other fees for additional services you may purchase, and any applicable taxes in connection with your use of the Services through the credit card or other payment method accepted by the Company (\"Payment Method\") that you provided during registration. If you want to use a different Payment Method than the one you signed up for during registration, or if there is a change in your credit card validity or expiration date, you may edit your Payment Method information by clicking on your account. If your Payment Method expires and you do not edit your Payment Method information or cancel your account, you authorize us to continue billing, and you will remain responsible for any uncollected amounts.\n" +
                "As used in these Terms, \"billing\" shall indicate either a charge or debit, as applicable, against your Payment Method. The subscription fee will be billed at the beginning of your subscription and on each subsequent renewal (as per plan chosen by you) thereafter unless and until you cancel your subscription or the account or service is otherwise suspended or discontinued pursuant to these Terms. To see the commencement date for your next renewal period, go to the billing information section on your account page.\n" +
                "In order to sustain the Services, it is important that you honor the payment obligations to which you have agreed. Accordingly, the Company reserves the right to pursue any amounts you fail to pay in connection with the Services. You will remain liable to the Company for all such amounts and all costs incurred by the Company in connection with the collection of these amounts, including, without limitation, collection agency fees, reasonable attorneys´ fees, and arbitration or court costs.\n" +
                "You also understand and acknowledge that the Company only facilitates the third party payment gateway for processing of payment. This facility is managed by the third party payment gateway provider and you are required to follow all the terms and conditions of such third party payment gateway provider. You are responsible for the accuracy and authenticity of the information provided by you, including the bank account number/credit card details and the like. You agree and acknowledge that the Company shall not be liable and in no way be held responsible for any losses whatsoever, whether direct, indirect, incidental or consequential, including without limitation any losses due to delay in processing of payment instruction or any credit card fraud.\n" +
                "You can file any complaint related to payment transfer at Site and the same shall be forwarded to the concerned third party payment gateway provider for redressal.\n" +
                "Free Trials: You may be offered a free trial period at the start of your membership of the Services, solely at the discretion of the Company. The duration and the terms of the free trial period shall be at the discretion of the Company and shall be specified during sign up. Free trials may not be combined with any other offer(s). Free trials will not be given in cases of renewal of membership or activation of another account from a physical address and/or email address and/or device which is linked to an already existing account, etc. Billing may automatically commence at the end the free trial period, without prior notice, as per the subscription plan chosen by you, unless you cancel your membership prior to the expiry of the free trial period. It is hence recommended that you keep track of your account, including the date when the free trial period ends.\n" +
                "Once billing commences, we will continue to bill your Payment Method for your membership fee until you cancel. You may cancel your membership at anytime; however, there are no refunds or credits for partially used periods.\n" +
                "\n" +
                "LINKS TO OTHER SITES\n" +
                "The Site or the Services may contain the links or pointers to other websites but you should not infer or assume that the Company operates, controls, or is otherwise connected with these other websites. When you click on a link within the Site, the Company may not warn you that you have left the Site and are subject to the terms and conditions (including privacy policies) of another website. Please be careful to read the terms of use and privacy policy of any other website before you provide any confidential information or engage in any transactions. You should not rely on these Terms to govern your use of another website.\n" +
                "The Company is not responsible for the content or practices of any other website even if it links to the Site and even if the website is operated by a company affiliated or otherwise connected with the Company. You acknowledge and agree that the Company is not responsible or liable to you for any content or other materials hosted and served from any website other than the Site.\n" +
                "\n" +
                "ADVERTISING MATERIAL\n" +
                "Part of the Site or the Services may contain advertising information or promotion material or other material submitted to the Company by third parties. Responsibility for ensuring that material submitted for inclusion on the Site complies with applicable international and national law is exclusively on the party providing the information/material. Your correspondence or business dealings with, or participation in promotions of advertisers including payment and delivery of related goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such advertiser. Before relying on any advertising material, you should independently verify its relevance for your purpose, and should obtain appropriate professional advice. The Company shall not be responsible nor liable for any loss or claim that you may have against an advertiser or any consequential damages arising on account of your relying on the contents of the advertisement.\n" +
                "\n" +
                "COLLECTION AND USE OF PERSONAL INFORMATION\n" +
                "For information about the Company´s policies and practices regarding the collection and use of your personally identifiable information, please read the Privacy Policy as available on the Site. The Privacy Policy is incorporated by reference and made part of these Terms. Thus, by agreeing to these Terms, you agree that your presence on the Site and use of the Services are governed by the Company’s Privacy Policy in effect at the time of your use. The Company reserves the right to disclose any information including the personal details that is required to be shared, disclosed or made available to any governmental, administrative, regulatory or judicial authority under any law or regulation applicable to the Company. The Company can further disclose your name, street address, city, state, zip code, country, phone number, email, as it in its sole discretion believes necessary or appropriate in connection with an investigation of fraud, intellectual property infringement, piracy, or other unlawful activity.\n" +
                "\n" +
                "YOUR OBLIGATIONS\n" +
                "You hereby agree and assure the Company that the Site and/or the Services shall be used for lawful purposes only and that you will not violate laws, regulations, ordinances or other such requirements of any applicable Central, State or local government or any other international laws. You specifically agree to comply with the requirements of the Information Technology Act, 2000 as also rules, regulations, guidelines, bye laws and notifications made thereunder, while on the Site. You further concur that you shall not:\n" +
                "circumvent, remove, alter, deactivate, degrade or thwart any of the content protections in the Site or the Services.\n" +
                "either directly or through the use of any device, software, internet site, web-based service, or other means copy, download, stream capture, reproduce, duplicate, archive, distribute, upload, publish, modify, transform, publish, translate, broadcast, perform, display, sell, transmit or retransmit the Content or any portion thereof or delete or fail to display any promotional taglines included in the Site / Service either directly or indirectly unless expressly permitted by the Company;\n" +
                "either directly or through the use of any device, software, internet site, web-based service, or other means remove, alter, bypass, avoid, interfere with, or circumvent any copyright, trademark, or other proprietary notices marked on the Content or any digital rights management mechanism, device, or other content protection or access control measure associated with the Content including geo-filtering mechanisms\n" +
                "use the Site or the Services in any manner that could damage, disable, overburden, or impair and not to undertake any action which is harmful or potentially harmful to any the Company´s server, or the network(s), computer systems / resource connected to any the Company server, or interfere with any other party´s use and enjoyment of the Site or the Services;\n" +
                "obtain or attempt to obtain any materials or information through any means not intentionally made available through the Site/Services;\n" +
                "perform any activity which is likely to cause such harm;\n" +
                "carry out any \"denial of service\" (DoS, DDoS) or any other harmful attacks on Site or internet service or;\n" +
                "use the Site or the Services for illegal or unlawful purposes;\n" +
                "disrupt, place unreasonable burdens or excessive loads on, interfere with or attempt to make or attempt any unauthorized access to the Site or any the Company website or the website of any the Company´s customer;\n" +
                "forge headers or otherwise manipulate identifiers in order to disguise the origin of any content transmitted through the Site or the Services;\n" +
                "attempt to gain unauthorized access to the Services, other accounts and computer systems through hacking, password mining or any other means. You shall not obtain or attempt to obtain any materials or information through any means not intentionally made available through the Site or the Services;\n" +
                "incorporate the Site or Services into or retransmit via, any hardware or software application or make it available via frames or in-line links unless expressly permitted by the Company in writing;\n" +
                "create, recreate, distribute or advertise an index of any significant portion of the Site or Services unless authorized by the Company;\n" +
                "use or launch any \"robots\", \"spiders\", \"offline readers\" etc. or any other automated system, that accesses the Site or the Services in a manner that sends numerous automated requests to the Site´s servers in a given period of time, which a human cannot reasonably send in the same period by using conventional web browsing application or tool(s) for similar purposes;\n" +
                "Send or post any unsolicited or unauthorized advertising, promotional materials, email, junk mail, spam, chain letters or other form of solicitation like solicit login information or access an account belonging to someone else;\n" +
                "Use the Site, Services or Company Content for any commercial purpose or the benefit of any third party or in any manner not permitted by these Terms of Use;\n" +
                "Impersonate or misrepresent your affiliation with any person or entity;\n" +
                "Encourage or enable any other individual to do any of the foregoing.\n" +
                "In addition, you are strictly prohibited from creating derivative works or materials that otherwise are derived from or based ,on the Content in any way, including montages, mash-ups and similar videos, wallpaper, desktop themes, greeting cards, and merchandise, unless it is expressly permitted by the Company in writing. This prohibition applies even if you intend to give away the derivative materials free of charge.\n" +
                "If you are a publisher of news and current affairs content, then in addition to compliance with other terms mentioned herein, you shall also furnish details of your user accounts on our services to the Ministry of Information and Broadcasting as required under the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021 (“Rules”) and you shall comply with all applicable laws including said Rules. TIL may, at its discretion, provide such publishers who have provided information under said Rules to the Ministry of Information and Broadcasting, a demonstrable and visible mark of verification as being publishers, which may be visible to all users of the service.\n" +
                "The Site may permit you to post user submissions including but not limited to reviews of Content available through the Services, comments on such Content etc. You understand that these User Submissions, once posted by you, are visible to all members since it is a public forum.\n" +
                "More specifically, when you review / rate any Content available on the Services (as per functionality made available on the Site), you give the Company express rights and consent to display your rating / review in relation to the relevant Content on the Site, including making it available to other members for viewing. If you do not want your User Submissions / reviews / ratings to be shared in a public forum, do not use these features.\n" +
                "These features may change without notice to you and the degrees of associated information sharing and functionality may also change without notice.\n" +
                "The Company is free to use any comments, information, ideas, concepts, reviews, or techniques or any other material contained in any communication you may send to us (\"User Feedback\"), including responses to questionnaires or through postings to the Services / the Site and User Submissions, without further compensation, acknowledgement or payment to you for any purpose whatsoever including, but not limited to, developing, manufacturing and marketing products and creating, modifying or improving the Services. By posting / submitting any User Feedback / User Submission on the Site, you grant the Company a perpetual, worldwide, non-exclusive, royalty-free irrevocable, sub-licensable license and right in such User Feedback / User Submission to the Company, including the right to display, use, reproduce or modify the User Feedback / User Submission in any media, software or technology of any kind now existing or developed in the future.\n" +
                "Operators of public search engines have the permission to use functionalities like spiders to copy materials from the Site for the sole purpose of creating publicly available searchable indices of the materials, but not caches or archives of such materials. We reserve the right to revoke these exceptions either generally or in specific cases, in our sole discretion. You agree not to collect or harvest any personally identifiable information, including account names, from the Site, nor to use the communication systems provided by the Site for any commercial solicitation purposes. You agree not to solicit, for commercial purposes, any users of the Site with respect to its User Submissions.\n" +
                "You shall be financially responsible for your use of the Services (as well as for use of your account by others, including without limitation minors living with you). You undertake to supervise and be responsible for all usage of minors and access of the Site under your name or account and absolve the Company from any liability on this account. You also warrant that all information supplied by you or members of your family for using the Services and accessing the Site, including without limitation your name, email address, street address, telephone number, mobile number, credit card number is correct and accurate. Failure to provide accurate information may subject you to civil and criminal penalties.\n" +
                "You shall be responsible for obtaining and maintaining any equipment or ancillary services needed to connect to, access the Site or otherwise use the Services, including, without limitation, modems, hardware, software, and long distance or local telephone service. You shall be responsible for ensuring that such equipment or ancillary services are compatible with the Services.\n" +
                "You agree that the Company may directly or through third party service providers send information to you about the various services offered by the Company from time to time.\n" +
                "You agree that Company will have the right to investigate and take all appropriate legal action to prevent, stop or deter violations of any of the above, including infringement of intellectual property rights and Site and Services security issues. Company may involve and cooperate with law enforcement authorities in prosecuting users who violate these Terms of Use or the rights of any third party.\n" +
                "You acknowledge that Company has no obligation to monitor your access to or use of the Site, Services or Company Content or to review or edit any User Submissions or Third Party Materials, but has the right to do so for the purpose of operating the Site and Services, to ensure your compliance with these Terms of Use, or to comply with applicable law or the order or requirement of a court, administrative agency or other governmental body. Company reserves the right, at any time and without prior notice, to remove or disable access to any Company Content, Third Party Materials, and any User Submissions and any other content, that Company, in its sole discretion, considers to be in violation of these Terms or otherwise harmful to the Site or Services.\n" +
                "\n" +
                "PROHIBITED ACTIVITIES\n" +
                "You agree not to host, display, upload, modify, publish, transmit, store, update or share any information or User Submissions which\n" +
                "belongs to another person and to which the user does not have any right;\n" +
                "is defamatory, obscene, pornographic, paedophilic, invasive of another‘s privacy, including bodily privacy, insulting or harassing on the basis of gender, libellous, racially or ethnically objectionable, relating or encouraging money laundering or gambling, or otherwise inconsistent with or contrary to the laws in force;\n" +
                "is harmful to child;\n" +
                "infringes any patent, trademark, copyright or other proprietary rights;\n" +
                "violates any law for the time being in force;\n" +
                "deceives or misleads the addressee about the origin of the message or knowingly and intentionally communicates any information which is patently false or misleading in nature but may reasonably be perceived as a fact;\n" +
                "impersonates another person;\n" +
                "threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign States, or public order, or causes incitement to the commission of any cognisable offence or prevents investigation of any offence or is insulting other nation;\n" +
                "contains software virus or any other computer code, file or program designed to interrupt, destroy or limit the functionality of any computer resource;\n" +
                "is patently false and untrue, and is written or published in any form, with the intent to mislead or harass a person, entity or agency for financial gain or to cause any injury to any person;\n" +
                "threatens public health or safety; promotion of cigarettes or any other tobacco products or consumption of intoxicant including alcohol and Electronic Nicotine Delivery System (ENDS) & like products that enable nicotine delivery except for the purpose & in the manner and to the extent, as may be approved under the Drugs and Cosmetics Act, 1940 and Rules made thereunder;\n" +
                "threatens critical information infrastructure\n" +
                "contain misleading information regarding the origin of the content; or\n" +
                "otherwise contains objectionable content.\n" +
                "\n" +
                "You understand and agree that the Company may, but is not obligated to, review the User Submissions and may delete or remove it (without notice) in its sole and absolute discretion, for any reason or without assigning any reason.\n" +
                "\n" +
                "Any content and or comment uploaded by you, shall be subject to relevant laws and may be disabled, or and may be subject to investigation under appropriate laws. If you are found to be in non-compliance with the laws and regulations, these terms, or the privacy policy of the Site, the Company shall have the right to immediately terminate/block your access and usage of the Site and the Company shall have the right to immediately remove any non-compliant content and or comment, uploaded by you subject to retaining such information as required under applicable laws and shall further have the right to take recourse to such remedies as would be available to the Company under the applicable laws. Additionally, unlawful content will be removed on being notified by a government agency or by an order of any court or as required under applicable laws.\n" +
                "\n" +
                "TIL reserves the right to preserve records of content transmitted by it as required under applicable laws.\n" +
                "\n" +
                "TERMINATION OF ACCOUNT, SUSPENSION OR DISCONTINUATION OF THE SERVICE\n" +
                "The Company reserves the right to change, suspend, or discontinue temporarily or permanently, some or all of the Services (including the Content and the devices through which the Services are accessed), with respect to any or all users, at any time without notice. You acknowledge that the Company may do so in its sole discretion. You also agree that the Company will not be liable to you for any modification, suspension, or discontinuance of the Services, although if you are a paid subscriber and the Company suspends or discontinues the Services, the Company may, in its sole discretion, provide you with a credit, refund, discount or other form of consideration (for example, the Company may credit additional days of service to your account). However, if the Company terminates your account or suspends or discontinues your access to the Services due to your violation of these Terms, then you will not be eligible for any such credit, refund, discount or other consideration.\n" +
                "Company may retain any information and associated records that are required to be retained or preserved under applicable laws including post termination of your account and irrespective of whether such information or content has been removed or access to it has been disabled.\n" +
                "\n" +
                "DISCLAIMER OF WARRANTIES AND LIABILITY\n" +
                "You understand and agree that the Company provides the Services on ´as-is´ ´with all faults´ and ´as available´ basis. You agree that use of the Site or the Services is at your risk. All warranties including without limitation, the implied warranties of merchantability, fitness for a particular purpose, for the title and non-infringement are disclaimed and excluded.\n" +
                "No representations, warranties or guarantees whatsoever are made by the Company as to the (a) accuracy, adequacy, reliability, completeness, suitability or applicability of the information to a particular situation; (b) that the service will be uninterrupted, timely, secure, or error-free; (c) the quality of any services, content, information, or other material on the website will meet your expectations or requirements; (d) any errors in the Site will be corrected; (e) warranties against infringement of any third party intellectual property or proprietary rights; or (f) other warranties relating to performance, non-performance, or other acts or omissions of the Company, its officers, directors, employees, affiliates, agents, licensors, or suppliers.\n" +
                "The Company does not warrant that any of the software used and or licensed in connection with the Services will be compatible with other third party software or devices nor does it warrant that operation of the Services and the associated software will not damage or disrupt other software or hardware.\n" +
                "\n" +
                "Under no circumstances will TIL be held responsible or liable, in any way, for any content which in Legal opinion is derogatory, threatening, defamatory, obscene or offensive or offends public sensibilities or morals and shall also not assume liability for any errors or omissions in any content, or for any loss or damage of any kind incurred as a result of the use of any content posted or uploaded on the Site, or any infringement of another's rights, including intellectual property rights. You specifically agree that TIL is not responsible for any content sent using and/or included in TIL's site/service by any third party.\n" +
                "The Company, its affiliates, successors, and assigns, and each of their respective investors, directors, officers, employees, agents, and suppliers (including distributors and content licensors) shall not be liable, at any time for any, direct, indirect, punitive, incidental, special, consequential, damages arising out of or in any way connected with the use of Site or the Services, whether based in contract, tort, strict liability, or other theory, even if the Company have been advised of the possibility of damages.\n" +
                "In the event any exclusion contained herein be held to be invalid for any reason and the Company or any of its affiliate entities, officers, directors or employees become liable for loss or damage, then, any such liability of the Company or any of its affiliate entities, officers, directors or employees shall be limited to not exceeding subscription charges paid by you in the month preceding the date of your claim for the particular subscription in question chosen by you.\n" +
                "\n" +
                "INDEMNIFICATION\n" +
                "You agree to indemnify, defend and hold harmless, the Company, its affiliates, successors, and assigns, and each of their respective investors, directors, officers, employees, agents, and suppliers (including distributors and content licensors) from and against any losses, claims, damages, liabilities, including legal fees and expenses, arising out of or in relation to:\n" +
                "your violation of these Terms, including but not limited to a claim arising out of a breach of your representations or warranties made hereunder;\n" +
                "your use or misuse of or access to the Site or the Services;\n" +
                "your violation of any law, regulation or third party right, including without limitation any copyright, property, or privacy right; or\n" +
                "any claim that you have caused damage to a third party.\n" +
                "any content or material submitted by you.\n" +
                "The Company reserves the right, at its own expense, to employ separate counsel and assume the exclusive defence and control of any matter otherwise subject to indemnification by you, and you agree to cooperate with the Company´s defence of these claims.\n" +
                "\n" +
                "GRIEVANCE REDRESSAL MECHANISM\n" +
                "Redressal Mechanism: Any complaints or concerns with regards to content and or comment or breach of these terms shall be taken up with the designated Grievance Officer as mentioned below via in writing or through email signed with the electronic signature to grievance at grievance.nbt@timesinternet.in or Mr. Akhilesh Shrivastava (\"Grievance Officer\")\n" +
                "Mr. Akhilesh Shrivastava\n" +
                "Grievance Officer\n" +
                "Times Internet Limited\n" +
                "Plot No. 391, Udyog Vihar, Phase-III, Gurgaon-122016, Haryana, India\n" +
                "Ph: 0124-4187000\n" +
                "Notice of Copyright Infringement: Our policy is to comply with all Intellectual Property Laws and to act expeditiously upon receiving any notice of claimed infringement. If you believe that any work has been reproduced on this Site in a manner that constitutes copyright infringement, please provide a notice of copyright infringement containing all of the following information:\n" +
                "A physical or electronic signature of a person authorized to act on behalf of the copyright owner for the purposes of the complaint.\n" +
                "Identification of the copyrighted work claimed to have been infringed.\n" +
                "Identification of the material on our Site that is claimed to be infringing or to be the subject of infringing activity.\n" +
                "The address, telephone number or e-mail address of the complaining party.\n" +
                "A statement that the complaining party has a good-faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent or the law.\n" +
                "A statement, under penalty of perjury, that the information in the notice of copyright infringement is accurate, and that the complaining party is authorized to act on behalf of the owner of the right that is allegedly infringed.\n" +
                "\n" +
                "GENERAL TERMS\n" +
                "Relationship\n" +
                "None of the provisions of the Terms shall be deemed to constitute a partnership or agency between you and the Company and you shall have no authority to bind the Company in any manner, whatsoever. This agreement is solely for your and the Company’s benefit and not for the benefit of any other person, except for permitted successors and assigns under this Agreement.\n" +
                "Assignment\n" +
                "You may not transfer to anyone else, either temporarily or permanently, any rights to use the Services or any part of the Services. Any attempt by you to do so is void. The Company may assign, transfer, delegate and/or grant all or any part of its rights, privileges and properties hereunder to any person or entity.\n" +
                "Force Majeure\n" +
                "Neither Party shall have any liability for any interruption or delay, to access the Site due to Force Majeure Event. For the purposes of this clause, ´Force Majeure Event´ means any event or circumstance or combination of events and circumstances which is reasonably beyond the control of the party affected thereby and which causes or results in default or delay in performance by such affected party of any of its obligations under this agreement and includes an act of God, war, hostilities, civil commotion, epidemics, lockdowns, strikes, lockouts and other industrial disputes.\n" +
                "Applicable Law\n" +
                "These Terms are governed by and construed in accordance with, the laws of India without giving effect to principles of conflict of law. In the event of any dispute or claim by you against the Company, you agree to submit to the exclusive jurisdiction of courts at New Delhi.\n" +
                "Limited Time To Bring Your Claim\n" +
                "You and the Company agree that any cause of action arising out of or related to use of the Site or the Services must commence within one (1) year after the cause of action accrues otherwise, such cause of action will be permanently barred.\n" +
                "Survival\n" +
                "Rights and obligations under the Terms which by their nature should survive will remain in full effect after termination or expiration of the subscription.\n" +
                "Non Waiver\n" +
                "Any express waiver or failure to exercise promptly any right under this agreement will not create a continuing waiver or any expectation of non-enforcement.\n" +
                "Entire Agreement\n" +
                "These Terms constitute the entire agreement between the parties with respect to the subject matter hereof and supersedes and replaces all prior or contemporaneous understandings or agreements, written or oral, regarding such subject matter.\n" +
                "Copyright Notice\n" +
                "Copyright ©2015 Times Internet Limited. All rights reserved.";

        textView.setText(para);

        textView.setMovementMethod(new ScrollingMovementMethod());
    }
}